### ISSUE TITLE
Autowatch opening pyxis

### ISSUE THREAD

**Issue by Brotocol** [sethmccauley/Addons#2]
Autowatch seems to work great for the main account that's popping the NM, but on slave accounts it spams about 1000 times and ends up crashing POL or breaking the chest. Any ideas as to why that would be happening? Great addon, thanks for any help you could provide.

**Comment by sethmccauley** [comment]
It spams opening the chest? Haven't had a slave do that yet on my end. If you can snag a screenshot or log file it may help.

I did have trouble with 'leech' settings, in the end I just left it alone because the mode was redundant. As 'slave' served the same purpose when engaged was set to off. 

I should just remove the leech mode from the lua.

**Comment by Brotocol** [comment]
Yeah I think it may have been on leech mode, been using slave mode for a few hours and it has been looting pretty consistently. The only thing that seems to cancel it is if an action is performed on the character opening at just the right time, they'll get "Event Skipped" and won't attempt to re-open the chest. Not a huge deal, and certainly better than it spamming and crashing itself lol.

**Comment by sethmccauley** [comment]
I had figured it was probably the leech mode. I'll be removing that function from the lua in the near future as to prevent this issue.

I think event skipped protection is probably outside of my intended design space, so I don't think I'll be looking into that level of prevention.

Hope you've been getting all the Heavy Metals!
