### ISSUE TITLE
sparks

### ISSUE THREAD

**Issue by CaiIsProgrammer** [sethmccauley/Addons#4]
when trying to load it says there a bunch of files missing after adding maps and sparks lua.

**Comment by sethmccauley** [comment]
It has been a long time since I've loaded and used the addon. It does strictly call for a few helpers, notably:

```
require('tables')
require('logger')
packets = require('packets')
db = require('map')
```

These helper files are normally preloaded within the windower addons folder structure. I'm not at my home pc or I could point you towards the location they should live.

Are you getting any other specific notices beyond the above?

**Comment by CaiIsProgrammer** [comment]
oh i think its because i use ashita

**Comment by sethmccauley** [comment]
As this add-on is intended for windower I'll close this issue.
